config/routes.rb
Rails.application.routes.draw do
  root 'items#index'
  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
      @items = Item.all
    end

    def new
      @item = Item.new
    end

    def edit
      @item = Item.find(params[:id])
    end

    def show
      @item = Item.find(params[:id])
    end

    def create
      @item = Item.new(item_params)
  # if Entry.create(entry_params)

      if @item.save
        redirect_to items_path
      else
        render :new
      end
    end

    def update
      @item = Item.find(params[:id])
      re
    end

private

    def item_params
      params.require(:item).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Edit TO DO(s) item</h1>
<%= form_for @item do |f| %>
  <%= f.label :name%>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<h1>To Do(s)</h1>
<p><%= link_to 'New TODO(s) item', new_item_path%></p>
<% @items.each do |item| %>
  <h2><%= item.name %></h2>
  <p><%= item.description %></p>
  <%= link_to 'Show Entry', item_path(item)%>
  <%= link_to 'Edit', edit_item_path(item)%>
  <%= link_to 'Delete', item_path(item), method: :delete %>

<% end %>

app/views/items/new.html.erb
<h1>What would you like to add to your TO DO(s) list?</h1>
  <%= form_for @item do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>